### ISSUE TITLE
Where are the electronics for Crazyflie 2?

### ISSUE THREAD

**Issue by whmountains** [bitcraze/crazyflie-electronics#1]
The website says all the hardware and software is open-source on GitHub, but I can't find the board files for the Crazyflie 2.0 anywhere.

Is that something you've chosen not to release, or am I just not looking hard enough?  Thanks a lot!

**Comment by tobbeanton** [comment]
Sorry, the KiCad files for Crazyflie 2.0 are not published publicly.

**Comment by tinkertux** [comment]
Where we can get the Kicad files for Crazyflie 2.0?
We can only get the PDF files for Crazyflie 2.0?

**Comment by ataffanel** [comment]
The Kicad files is something we have not published yet. So yes you can only get the PDFs schematic and  component placement of Crazyflie 2.0.

**Comment by tinkertux** [comment]
OK！Thank you！

**Comment by lurenaud** [comment]
Hello,
Do you have any news about the kicad files release date ?
(Just out of curiosity, is there a reason for not publish it from the start ?)
Thank you !
